# Makefile.deps created Tue Sep  6 16:11:28 PDT 2016
absyn.cmo :
absyn.cmx :
etc.cmi :
etc.cmo : etc.cmi
etc.cmx : etc.cmi
lexer.cmo : parser.cmi etc.cmi absyn.cmo
lexer.cmx : parser.cmx etc.cmx absyn.cmx
main.cmo : parser.cmi lexer.cmo etc.cmi absyn.cmo
main.cmx : parser.cmx lexer.cmx etc.cmx absyn.cmx
parser.cmi : absyn.cmo
parser.cmo : etc.cmi absyn.cmo parser.cmi
parser.cmx : etc.cmx absyn.cmx parser.cmi
